import os
import re
import uuid
from datetime import datetime
from typing import Dict, Any, Optional

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import inch

PDF_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "generated_pdfs")
os.makedirs(PDF_DIR, exist_ok=True)

def generate_pdf_document(title: str, content: str, author: str = "Aisia Autonomous AI") -> Dict[str, Any]:
    """
    Autonomously generates an executive-grade, beautifully formatted PDF report or document.
    """
    try:
        clean_title = title.strip() or "Aisia Document Report"
        slug = re.sub(r'[^a-zA-Z0-9_\-]', '_', clean_title.lower())[:32].strip('_')
        unique_id = uuid.uuid4().hex[:6]
        filename = f"{slug}_{unique_id}.pdf"
        file_path = os.path.join(PDF_DIR, filename)

        doc = SimpleDocTemplate(
            file_path,
            pagesize=letter,
            rightMargin=48,
            leftMargin=48,
            topMargin=48,
            bottomMargin=48
        )

        styles = getSampleStyleSheet()
        
        # Custom Typography Styles
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#0f172a'),
            spaceAfter=6
        )

        subtitle_style = ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#64748b'),
            spaceAfter=14
        )

        h1_style = ParagraphStyle(
            'H1Style',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#1e293b'),
            spaceBefore=12,
            spaceAfter=6
        )

        h2_style = ParagraphStyle(
            'H2Style',
            parent=styles['Heading3'],
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=16,
            textColor=colors.HexColor('#334155'),
            spaceBefore=10,
            spaceAfter=4
        )

        body_style = ParagraphStyle(
            'ReportBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=15,
            textColor=colors.HexColor('#334155'),
            spaceAfter=8
        )

        bullet_style = ParagraphStyle(
            'ReportBullet',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=15,
            textColor=colors.HexColor('#334155'),
            leftIndent=16,
            spaceAfter=4
        )

        callout_style = ParagraphStyle(
            'CalloutStyle',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=9.5,
            leading=14,
            textColor=colors.HexColor('#0284c7'),
            spaceBefore=6,
            spaceAfter=8
        )

        story = []

        # 1. Header Banner
        story.append(Paragraph(clean_title, title_style))
        now_str = datetime.now().strftime("%B %d, %Y • %I:%M %p")
        meta_text = f"Generated by <b>{author}</b> • {now_str} • Verified Output"
        story.append(Paragraph(meta_text, subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#38bdf8'), spaceAfter=14))

        # 2. Parse Markdown-like Content
        lines = content.split('\n')
        for raw_line in lines:
            line = raw_line.strip()
            if not line:
                story.append(Spacer(1, 6))
                continue

            # Headers
            if line.startswith('### '):
                heading = line[4:].replace('**', '')
                story.append(Paragraph(heading, h2_style))
            elif line.startswith('## '):
                heading = line[3:].replace('**', '')
                story.append(Paragraph(heading, h1_style))
            elif line.startswith('# '):
                heading = line[2:].replace('**', '')
                story.append(Paragraph(heading, h1_style))
            elif line.startswith('- ') or line.startswith('* ') or line.startswith('• '):
                bullet_text = line[2:].strip()
                # Format bold tags
                formatted = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', bullet_text)
                story.append(Paragraph(f"• {formatted}", bullet_style))
            elif re.match(r'^\d+\.\s+', line):
                formatted = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
                story.append(Paragraph(formatted, bullet_style))
            elif line.startswith('> '):
                quote = line[2:].strip()
                formatted = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', quote)
                story.append(Paragraph(formatted, callout_style))
            elif line.startswith('---'):
                story.append(HRFlowable(width="100%", thickness=0.8, color=colors.HexColor('#e2e8f0'), spaceBefore=8, spaceAfter=8))
            else:
                formatted = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
                story.append(Paragraph(formatted, body_style))

        # 3. Footer Spacer & Branding Note
        story.append(Spacer(1, 16))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#cbd5e1'), spaceAfter=8))
        footer_style = ParagraphStyle(
            'FooterStyle',
            fontName='Helvetica',
            fontSize=8,
            leading=10,
            textColor=colors.HexColor('#94a3b8'),
            alignment=1 # Centered
        )
        story.append(Paragraph("Aisia Autonomous Agent System • Studio Intelligence Suite", footer_style))

        # Build PDF
        doc.build(story)

        file_size = os.path.getsize(file_path)
        download_url = f"http://localhost:8000/pdf/download/{filename}"
        view_url = f"http://localhost:8000/pdf/view/{filename}"

        return {
            "success": True,
            "filename": filename,
            "title": clean_title,
            "size_bytes": file_size,
            "size_kb": round(file_size / 1024, 1),
            "file_path": file_path,
            "download_url": download_url,
            "view_url": view_url,
            "message": f"Successfully generated PDF '{clean_title}' ({round(file_size/1024, 1)} KB). Download available at {download_url}"
        }

    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "message": f"Failed to generate PDF: {str(e)}"
        }
